#!/bin/bash
echo "Begin";
mkdir -p /backup/;
tar -czf /backup/$(hostname -s)-$(date +'%y.%m.%d-%H.%M.%S').tgz /etc;
echo "End"
echo "SOSI HUI SOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUISOSI HUI"
# tar -tf - просмотр архива
# tar -xvzf - распакоука
